### ISSUE TITLE
Highcharts.jsの商用利用が有償のため、他のライブラリを選定する。

### ISSUE THREAD

**Issue by KaiShoya** [lumbermill/takachiho#69]

**Comment by yosei** [comment]
ライセンス買ったほうが速い（安い）のでは…？

**Comment by yosei** [comment]
chartsjsが一番手かな…？
http://www.chartjs.org/
http://canvasjs.com/
https://plot.ly/

https://www.quora.com/What-are-some-good-alternatives-to-Highcharts-for-a-charting-library-used-in-a-data-visualization-tool
http://qiita.com/awakia/items/d064c772b759333c209a

**Comment by yosei** [comment]
Google Chartsに移行済み
