### ISSUE TITLE
「oo 人が閲覧中」のラベル実装

### ISSUE THREAD

**Issue by yosei** [lumbermill/takachiho#70]
10分以内にページをロードしたセッションの数を保持しておきます。
ファイルに数値を保持しようと思ったけれど、排他制御が心配だし、デクリメントもうまくできないはず。

という訳でセッションIDと最終アクセス日時をページ(raspi_id)ごとに保持するテーブルが必要かも？
` raspi_id integer session_id last_accessed_at datetime`

**Comment by KaiShoya** [comment]
82e40ad
