### ISSUE TITLE
[mukoyama]日中の屋外撮影で白飛びする

### ISSUE THREAD

**Issue by koki-h** [lumbermill/takachiho#85]
以下のブランチにて対応中
https://github.com/lumbermill/takachiho/tree/mukoyama_outdoor_shot

see：
c53b4020430d7bf8f066fd9484347659702a8dc8
32c365601e7af8770a5a596a29da36c6236bce03

**Comment by koki-h** [comment]
天候曇り 朝９時頃
対応前
![170427_090002](https://cloud.githubusercontent.com/assets/52752/25462862/ea79b262-2b2c-11e7-95fd-31739ee80c74.jpg)

対応後
![170427_090331](https://cloud.githubusercontent.com/assets/52752/25462861/ea738946-2b2c-11e7-961b-8faa2eff651c.jpg)

だいぶ白飛びが軽減された。晴天時の日中と、夜間も様子を見る。

**Comment by koki-h** [comment]
夜間、日中でも白飛びの軽減が確認できた。

適用後、夜間（2017/04/27 19:30）
![img_1345](https://cloud.githubusercontent.com/assets/52752/25514094/468456dc-2c15-11e7-8a41-b560cee6a970.JPG)

適用後、晴天時早朝。直射日光が差し込んだ時（2017/04/28 07:13）
![img_1357](https://cloud.githubusercontent.com/assets/52752/25514151/b6b51856-2c15-11e7-8921-942fb757e191.JPG)


適用後、晴天の日中（2017/04/28 13:13）
![170428_131305](https://cloud.githubusercontent.com/assets/52752/25514114/74304adc-2c15-11e7-9894-83508dcb85bc.jpg)

**Comment by yosei** [comment]
この設定で室内も問題なければブランチをマージしちゃって良さそうですね。

**Comment by koki-h** [comment]
室内で試してみました。オートホワイトバランスを太陽光モードにしているせいか、黄色っぽくなって夕方みたいですね（朝なのに）。

適用前
![170508_094001](https://cloud.githubusercontent.com/assets/52752/25786640/8c9091de-33d3-11e7-8960-0f30c9ce62d7.jpg)

適用後
![170508_094405](https://cloud.githubusercontent.com/assets/52752/25786643/8ef1c376-33d3-11e7-8bd7-434a1de0eadb.jpg)
